# Generated by Django 4.2.1 on 2023-05-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BookListAPI", "0003_alter_book_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="category",
        ),
    ]
